# SPDX-FileCopyrightText: 2024 Stichting Health-RI
# SPDX-FileContributor: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

name: Make Github release

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version increment (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
    # ort:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: oss-review-toolkit/ort-ci-github-action@v1
  #       with:
  #         allow-dynamic-versions: "true"
  #         fail-on: "issues"
  #         run: "cache-dependencies,cache-scan-results,labels,analyzer,evaluator,advisor,reporter,upload-results"

  versioning:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tagging.outputs.new_tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git User Identity
        run: |
          git config --local user.email "Health-RI-admin@users.noreply.github.com"
          git config --local user.name "Health-RI Admin" 

      - name: Fetch Latest Tag and Increment Version
        id: tagging
        run: |
          LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
          echo "Latest tag: $LATEST_TAG"
          
          # Extract Major, Minor, Patch
          IFS='.' read -r MAJOR MINOR PATCH <<<"${LATEST_TAG//v/}"
          INCREMENT=${{ github.event.inputs.version }}
          echo "Updating : $INCREMENT version"
          
          case "$INCREMENT" in
            major) MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
            minor) MINOR=$((MINOR + 1)); PATCH=0 ;;
            patch|*) PATCH=$((PATCH + 1)) ;;
          esac

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "Pushing this tag: $NEW_TAG"
          
          git tag -a "$NEW_TAG" -m "Release $NEW_TAG"
          git push origin "$NEW_TAG"

          echo "New tag pushed: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
  publish-release:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Generate and Publish GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG="${{ needs.versioning.outputs.new_tag }}"
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n '2p')

          echo "Creating GitHub release for $LATEST_TAG from previous release $PREVIOUS_TAG"
          
          gh release create "$LATEST_TAG" \
            --title "Release $LATEST_TAG" \
            --generate-notes \
            --notes-start-tag "$PREVIOUS_TAG"

  call-generate-changelog:
    needs: [versioning, publish-release]
    uses: ./.github/workflows/generate_changelog.yml
    with:
      tag: ${{ needs.versioning.outputs.new_tag }}

  docker-release:
    runs-on: ubuntu-latest
    needs: [versioning, publish-release, call-generate-changelog]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Docker tags
        id: docker_meta
        run: |
          VERSION="${{ needs.versioning.outputs.new_tag }}"
          VERSION="${VERSION#v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            healthri/fdp-schema-update-tool:${{ steps.docker_meta.outputs.version }}
            healthri/fdp-schema-update-tool:latest
